dependecies:
  #<organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
dotenv: .env
networks:
  default: development
  kovan:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
